# Generated by Django 4.2.16 on 2024-11-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('power_level', models.IntegerField()),
                ('is_grumpy', models.BooleanField(default=True)),
            ],
        ),
    ]
